language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=calendar_sms.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 --exclude=migrations calendar_sms
script:
  - coverage run --branch --source=calendar_sms `which django-admin.py` test calendar_sms
  - coverage report --omit="calendar_sms/test*"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6
branches:
  only:
    - master
    - development
after_success: coveralls
