language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=calendarsms.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 calendarsms
script:
  - coverage run --branch --source=calendarsms `which django-admin.py` test calendarsms
  - coverage report --omit="calendarsms/test*"
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
branches:
  only:
    - master
